[package]
name = "Server_Example"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["tls", "json"] }
rocket_ws = "0.1.1"
rocket_db_pools = { version = "0.2.0", features = ["mongodb"] }