# All The Config That can be Set
[default]
address = "127.0.0.1"
port = 443
workers = 16
max_blocking = 512
keep_alive = 5
ident = "Rocket"
ip_header = "X-Real-IP" # set to `false` to disable
log_level = "normal"
# temp_dir = "/tmp"
cli_colors = true
# secret_key = ""

# [default.limits]
# form = "64 kB"
# json = "1 MiB"
# msgpack = "2 MiB"
# "file/jpg" = "5 MiB"

[default.tls]
key = "certs/key.pem"
certs = "certs/cert.pem"

# [default.shutdown]
# ctrlc = true
# signals = ["term", "hup"]
# grace = 5
# mercy = 5

[default.databases.mongodb]
url = "mongodb://localhost:27017"

# Optional settings for MongoDB
# max_connections = 1024
# connect_timeout = 5
# idle_timeout = 120

